This is a dataset of regional US cuisine that has been scraped from the "List of Regional Dishes of the United States" Wikipedia page (https://en.wikipedia.org/wiki/List_of_regional_dishes_of_the_United_States#City_chicken). Scraped with beautiful soup, (sorta) standardized with Python, and then manually organized to account for hard to deal with data.

In [3]:
import pandas as pd 
import geopandas as gpd

foods_csv = '/Users/benmccarthy/Development/data_projects/regional_foods/regional_foods_EDITED_FOR_PROJ_4.csv'
foods_df = pd.read_csv(foods_csv)


states_geojson = '/Users/benmccarthy/Development/data_projects/regional_foods/states_geojson.json'
states_gdf = gpd.read_file(states_geojson, engine="pyogrio")
# states_gdf

# foods_df

geographies = []
# iterate thorugh foods, clean data, 
for index, row in foods_df.iterrows():
    # use eval to replace nasty little weird ass quotes
    
    state_list = eval(row['state'].replace("’","'").replace("‘","'").replace('"',"'").replace('”',"'").replace('“',"'"))
    # logic to handle rows without states (only regions, multiple regions, sub-regions) for later date. 
    # if len(state_list) == 0:
    #     print(row['region'])
    #     if row['region'] == 'Multiple':
    #         print(row['sub-region'])
    for state in state_list:
        # how does this filter work? 
        # we are looping through foods, with a nested loop looping through the states array of foods. 
        # state is the state from foods
        # if we find a match in states_gdf (states and geometries gdf) we create an obj with state name and geometry ->
        # and spread the rest of the row from foods_df to the new obj. 
        search = states_gdf[states_gdf['NAME'] == state]
        # else branch for when there is no state or states, replace with states from region?
        # print(len(search))
        if len(search):
            # append to geographies array, which we will turn into our own new df
            
            geographies.append({
                'geometry': search.iloc[0].geometry,
                'state' : state,
                # spread rows
                **row
            })

In [4]:
# foods_with_geographies_gpd = gpd.GeoDataFrame(geographies, crs='4326')
# foods_with_geographies_gpd
# geographies_gpd.to_file("/Users/benmccarthy/Development/data_projects/Jupyter.geojson", driver="GeoJSON")

This gives me a gdf of many geometries of states, each with a corresponding food. But for my leaflet app, where I want a user to be able to click a state and get a list of foods from that state, I need to condense the foods into the (less than 50) states. How do I do this?

for each row in the foods_with_geographies gpd, i need to loop through the states within the states column, and add each food (row) to an existing state in array format within an obj. 

Is it best to start over and do this in reverse from how I did it before? Taking the states_gdf and appending food info to it in a loop?

In [15]:
import ast

def parse_list(val):
    if isinstance(val, list):
        return val
    if isinstance(val, str):
        val = val.replace("’","'").replace("‘","'").replace('"',"'").replace('”',"'").replace('“',"'")
        return ast.literal_eval(val)
    return []

# this should have one state for every state in the states_geographies gdf
# create a new column that is an array of food properties
states_with_foods_obj_array = []
# loop through states with geographies
for index, state_with_geography in states_gdf.iterrows():
    # print(state_with_geography)
    # for every state_w_geo loop through foods. Check state column, loop through state array.
    # if food state matches geo_state, append to a new array within the state object
    new_state_with_geometry_and_foods_array = {
                    **state_with_geography,
                    'foods_array' : []
                }
    state_name_with_geography = state_with_geography['NAME']
    for index, food_row in foods_df.iterrows():
        state_name_array_from_foods = eval(food_row['state'].replace("’","'").replace("‘","'").replace('"',"'").replace('”',"'").replace('“',"'"))
        for state_name_from_food in state_name_array_from_foods:
            # print(state_name_from_food)
            # if state_name_from_food == state_name_with_geography, append food info obj to state obj
            if (state_name_from_food == state_name_with_geography):
                # print(food_row.state, state_name_with_geography)
                # print(state_with_geography, food_row)
                # create an object from state_geographies, with a food key with arr val that contains food_row objs
                # food_row_obj (type, dish, region, state, city, sub-region, location, description, image_url, citations)
                # state_geometry obj spread? where should this obj live? in top loop
                
                # image_url_modified = None
                # if food_row.image_url
                new_food_obj = {
                    'type': food_row.type,
                    'dish' : food_row.dish,
                    'region' : food_row.region,
                    'state' : parse_list(food_row.state),
                    'city' : parse_list(food_row.city),
                    'sub-region' : parse_list(food_row['sub-region']),
                    'location' : food_row.location,
                    'description' : food_row.description,
                    'image_url' : food_row.image_url
                }
                # append new object to obj within state/geo loop
                new_state_with_geometry_and_foods_array['foods_array'].append(new_food_obj)
    # append to main array (states_with_foods_obj_array)
    states_with_foods_obj_array.append(new_state_with_geometry_and_foods_array)

         
states_with_geographies_and_foods_gdf = gpd.GeoDataFrame(states_with_foods_obj_array, crs='4326')
# states_with_geographies_and_foods_gdf.iloc[6].foods_array
states_with_geographies_and_foods_gdf

,GEO_ID,STATE,NAME,LSAD,CENSUSAREA,geometry,foods_array
0,0400000US23,23,Maine,,30842.923,"MULTIPOLYGON (((-67.61976 44.51975, -67.61541 ...","[{'type': 'Desserts and confectionery', 'dish'..."
1,0400000US25,25,Massachusetts,,7800.058,"MULTIPOLYGON (((-70.83204 41.60650, -70.82373 ...","[{'type': 'General Cuisine', 'dish': 'Boston b..."
2,0400000US26,26,Michigan,,56538.901,"MULTIPOLYGON (((-88.68443 48.11579, -88.67563 ...","[{'type': 'General Cuisine', 'dish': 'City chi..."
3,0400000US30,30,Montana,,145545.801,"POLYGON ((-104.05770 44.99743, -104.25015 44.9...",[]
4,0400000US32,32,Nevada,,109781.180,"POLYGON ((-114.05060 37.00040, -114.04999 36.9...",[]
5,0400000US34,34,New Jersey,,7354.220,"POLYGON ((-75.52684 39.65571, -75.52634 39.656...","[{'type': 'General Cuisine', 'dish': 'Pork rol..."
6,0400000US36,36,New York,,47126.399,"MULTIPOLYGON (((-71.94356 41.28668, -71.92680 ...","[{'type': 'General Cuisine', 'dish': 'Baked zi..."
7,0400000US37,37,North Carolina,,48617.905,"MULTIPOLYGON (((-82.60288 36.03983, -82.60074 ...","[{'type': 'General Cuisine', 'dish': 'Livermus..."
8,0400000US39,39,Ohio,,40860.694,"MULTIPOLYGON (((-82.81349 41.72347, -82.81049 ...","[{'type': 'General Cuisine', 'dish': 'Cincinna..."
9,0400000US42,42,Pennsylvania,,44742.703,"POLYGON ((-75.41504 39.80179, -75.42804 39.809...","[{'type': 'General Cuisine', 'dish': 'City chi..."
10,0400000US44,44,Rhode Island,,1033.814,"MULTIPOLYGON (((-71.28157 41.64821, -71.27817 ...","[{'type': 'Fish and seafood dishes', 'dish': '..."
11,0400000US47,47,Tennessee,,41234.896,"POLYGON ((-81.67754 36.58812, -81.68014 36.585...","[{'type': 'Barbecue', 'dish': 'Barbecue spaghe..."
12,0400000US48,48,Texas,,261231.711,"MULTIPOLYGON (((-97.13436 27.89633, -97.13360 ...","[{'type': 'General Cuisine', 'dish': 'Borracho..."
13,0400000US49,49,Utah,,82169.620,"POLYGON ((-114.05060 37.00040, -114.05175 37.0...","[{'type': 'Chicken dishes', 'dish': 'Hawaiian ..."
14,0400000US53,53,Washington,,66455.521,"MULTIPOLYGON (((-123.09055 49.00198, -123.0353...","[{'type': 'Desserts and confectionery', 'dish'..."
15,0400000US55,55,Wisconsin,,54157.805,"MULTIPOLYGON (((-90.45525 47.02400, -90.45713 ...","[{'type': 'General Cuisine', 'dish': 'Fried ch..."
16,0400000US72,72,Puerto Rico,,3423.775,"MULTIPOLYGON (((-65.58733 18.38199, -65.59122 ...",[]
17,0400000US24,24,Maryland,,9707.241,"MULTIPOLYGON (((-76.07147 38.20350, -76.04879 ...","[{'type': 'Chicken dishes', 'dish': 'Chicken M..."
18,0400000US01,01,Alabama,,50645.326,"MULTIPOLYGON (((-85.00237 31.00068, -85.02411 ...","[{'type': 'Barbecue', 'dish': 'Alabama-style b..."
19,0400000US02,02,Alaska,,570640.950,"MULTIPOLYGON (((-164.97620 54.13459, -164.9377...",[]
20,0400000US04,04,Arizona,,113594.084,"POLYGON ((-109.04522 36.99908, -109.04524 36.9...","[{'type': 'General Cuisine', 'dish': 'Arizona ..."
21,0400000US05,05,Arkansas,,52035.477,"POLYGON ((-94.55929 36.49950, -94.51948 36.499...",[]
22,0400000US06,06,California,,155779.220,"MULTIPOLYGON (((-122.44632 37.86105, -122.4385...","[{'type': 'General Cuisine', 'dish': 'Joe's Sp..."
23,0400000US08,08,Colorado,,103641.888,"POLYGON ((-102.04224 36.99308, -102.05450 36.9...","[{'type': 'General Cuisine', 'dish': 'Rocky Mo..."
24,0400000US09,09,Connecticut,,4842.355,"MULTIPOLYGON (((-71.85957 41.32240, -71.86823 ...","[{'type': 'Pizza', 'dish': 'New Haven-style pi..."
25,0400000US10,10,Delaware,,1948.543,"MULTIPOLYGON (((-75.55945 39.62981, -75.55910 ...","[{'type': 'General Cuisine', 'dish': 'Scrapple..."
26,0400000US11,11,District of Columbia,,61.048,"POLYGON ((-77.03860 38.79151, -77.03890 38.800...",[]
27,0400000US12,12,Florida,,53624.759,"MULTIPOLYGON (((-85.15641 29.67963, -85.13740 ...","[{'type': 'Desserts and confectionery', 'dish'..."
28,0400000US13,13,Georgia,,57513.485,"POLYGON ((-81.44412 30.70971, -81.44872 30.709...","[{'type': 'Chicken dishes', 'dish': 'Lemon pep..."
29,0400000US15,15,Hawaii,,6422.628,"MULTIPOLYGON (((-171.73761 25.79210, -171.7223...","[{'type': 'General Cuisine', 'dish': 'Laulau',..."
30,0400000US16,16,Idaho,,82643.117,"POLYGON ((-111.04669 42.00157, -111.41587 42.0...","[{'type': 'Chicken dishes', 'dish': 'Hawaiian ..."
31,0400000US17,17,Illinois,,55518.930,"POLYGON ((-87.53233 39.99778, -87.53254 39.987...","[{'type': 'Barbecue', 'dish': 'Chicago-style b..."
32,0400000US18,18,Indiana,,35826.109,"POLYGON ((-88.02803 37.79922, -88.02938 37.803...","[{'type': 'General Cuisine', 'dish': 'City chi..."
33,0400000US19,19,Iowa,,55857.130,"POLYGON ((-95.76565 40.58521, -95.75889 40.588...","[{'type': 'Desserts and confectionery', 'dish'..."
34,0400000US20,20,Kansas,,81758.717,"POLYGON ((-94.61808 36.99813, -94.62522 36.998...","[{'type': 'Sandwiches', 'dish': 'Runza', 'regi..."
35,0400000US21,21,Kentucky,,39486.338,"MULTIPOLYGON (((-83.67541 36.60081, -83.67561 ...","[{'type': 'General Cuisine', 'dish': 'Lamb fri..."
36,0400000US22,22,Louisiana,,43203.905,"MULTIPOLYGON (((-88.86507 29.75271, -88.88975 ...","[{'type': 'General Cuisine', 'dish': 'Eggs Sar..."
37,0400000US27,27,Minnesota,,79626.743,"POLYGON ((-91.37161 43.50095, -91.37695 43.500...","[{'type': 'General Cuisine', 'dish': 'Hotdish'..."
38,0400000US28,28,Mississippi,,46923.274,"MULTIPOLYGON (((-88.71072 30.25080, -88.65680 ...","[{'type': 'Desserts and confectionery', 'dish'..."
39,0400000US29,29,Missouri,,68741.522,"POLYGON ((-89.53910 36.49820, -89.53452 36.491...","[{'type': 'General Cuisine', 'dish': 'Slinger'..."
40,0400000US31,31,Nebraska,,76824.171,"POLYGON ((-95.76565 40.58521, -95.76853 40.583...","[{'type': 'Sandwiches', 'dish': 'Reuben sandwi..."
41,0400000US33,33,New Hampshire,,8952.651,"MULTIPOLYGON (((-72.45852 42.72685, -72.45849 ...",[]
42,0400000US35,35,New Mexico,,121298.148,"POLYGON ((-109.05004 31.33250, -109.05017 31.4...","[{'type': 'General Cuisine', 'dish': 'Breakfas..."
43,0400000US38,38,North Dakota,,69000.798,"POLYGON ((-96.56328 45.93524, -96.57690 45.935...",[]
44,0400000US40,40,Oklahoma,,68594.921,"POLYGON ((-94.61792 36.49941, -94.61531 36.484...","[{'type': 'Barbecue', 'dish': 'Barbecue bologn..."
45,0400000US41,41,Oregon,,95988.013,"POLYGON ((-117.22007 44.30138, -117.22245 44.2...",[]
46,0400000US45,45,South Carolina,,30060.696,"POLYGON ((-78.54109 33.85111, -78.55394 33.847...","[{'type': 'Barbecue', 'dish': 'South Carolina-..."
47,0400000US46,46,South Dakota,,75811.000,"POLYGON ((-96.44341 42.48949, -96.45971 42.486...","[{'type': 'Barbecue', 'dish': 'Chislic', 'regi..."
48,0400000US50,50,Vermont,,9216.657,"POLYGON ((-72.04008 44.15575, -72.04271 44.152...","[{'type': 'Desserts and confectionery', 'dish'..."
49,0400000US51,51,Virginia,,39490.086,"MULTIPOLYGON (((-76.04653 37.95359, -76.04169 ...","[{'type': 'Desserts and confectionery', 'dish'..."
50,0400000US54,54,West Virginia,,24038.210,"POLYGON ((-81.96830 37.53780, -81.96540 37.541...","[{'type': 'Hot dogs and sausages', 'dish': 'Pe..."
51,0400000US56,56,Wyoming,,97093.141,"POLYGON ((-109.05008 41.00066, -109.17368 41.0...",[]

In [16]:
# states_with_geographies_and_foods_gdf.to_file("/Users/benmccarthy/Development/data_projects/States_with_foods_5.geojson", driver="GeoJSON", engine="pyogrio")

In [48]:
# 
states_with_dishes = []
for index, state_with_foods in states_with_geographies_and_foods_gdf.iterrows():
    
    # print(state_with_foods['NAME'], len(states_with_geographies_and_foods_gdf['foods_array'].iloc[index])) 
    name = state_with_foods['NAME']
    count = len(states_with_geographies_and_foods_gdf['foods_array'].iloc[index])
    count_obj = {
        "state" : name,
        "dishes" : count
    }
    states_with_dishes.append(count_obj)
sorted_states = sorted(states_with_dishes, key=lambda f: f['dishes'], reverse=True)

States_with_dish_count_df = pd.DataFrame(sorted_states)

States_with_dish_count_df

                   state  dishes
0               New York      48
1              Louisiana      26
2             California      23
3           Pennsylvania      18
4               Illinois      15
5                  Texas      14
6                 Hawaii      12
7                   Ohio      11
8               Missouri      10
9             New Jersey       8
10        North Carolina       8
11              Maryland       8
12               Indiana       8
13         Massachusetts       7
14              Michigan       7
15            Washington       7
16             Wisconsin       7
17              Kentucky       7
18        South Carolina       7
19                  Iowa       6
20             Minnesota       6
21             Tennessee       5
22          Rhode Island       4
23                  Utah       4
24              Colorado       4
25               Florida       4
26               Georgia       4
27                 Idaho       4
28           Mississippi       4
29               Arizona       3
30            New Mexico       3
31              Oklahoma       3
32              Virginia       3
33         West Virginia       3
34                 Maine       2
35               Alabama       2
36           Connecticut       2
37              Nebraska       2
38              Delaware       1
39                Kansas       1
40          South Dakota       1
41               Vermont       1
42               Montana       0
43                Nevada       0
44           Puerto Rico       0
45                Alaska       0
46              Arkansas       0
47  District of Columbia       0
48         New Hampshire       0
49          North Dakota       0
50                Oregon       0
51               Wyoming       0